#version: '3.8'
#services:
#  db:
#    container_name: pg_container
#    image: postgres
#    restart: always
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: password
#      POSTGRES_DB: realty_agency
#    ports:
#      - "5432:5432"
version: '3.8'
services:
  db:
    container_name: pg_container_deploy
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: realty_db_v7b3_user
      POSTGRES_PASSWORD: nPicQ7xgEPbZgFDH6UdAGLcJ3YbVha6C
      POSTGRES_DB: realty_db_v7b3
    ports:
      - "5432:5432"
#  pgadmin:
#    container_name: pgadmin4_container
#    image: dpage/pgadmin4
#    restart: always
#    environment:
#      PGADMIN_DEFAULT_EMAIL: admin@admin.com
#      PGADMIN_DEFAULT_PASSWORD: root
#    ports:
#      - "5050:80"