server:
  port: 8081
spring:
  datasource:
    #    url: jdbc:postgresql://localhost:5432/postgres
    url: jdbc:postgresql://dpg-ckhbgjmafg7c73956cs0-a.oregon-postgres.render.com:5432/realty_db_v7b3
    username: realty_db_v7b3_user
    password: nPicQ7xgEPbZgFDH6UdAGLcJ3YbVha6C
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      #      dialect: org.hibernate.dialect.PostgreSQLDialect
      database-platform: org.hibernate.dialect.PostgreSQLDialect
#server:
#  port: 8081
#spring:
#  datasource:
##    url: jdbc:postgresql://localhost:5432/postgres
#    url: jdbc:postgresql://localhost:5432/realty_agency?prepareThreshold=0
#    username: postgres
#    password: password
#    driverClassName: org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
##      dialect: org.hibernate.dialect.PostgreSQLDialect
#      database-platform: org.hibernate.dialect.PostgreSQLDialect
